<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.9Ox2ZFK' shared service.

return $this->privates['service_locator.9Ox2ZFK'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('twig' => function () {
    return ($this->services['twig'] ?? $this->getTwigService());
}));
