<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\Controller\LoginController' shared autowired service.

include_once $this->targetDirs[3].'\\src\\Controller\\LoginController.php';

return $this->services['App\Controller\LoginController'] = new \App\Controller\LoginController();
