<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVL31OCz\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVL31OCz/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerVL31OCz.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerVL31OCz\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerVL31OCz\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'VL31OCz',
    'container.build_id' => 'e777a1de',
    'container.build_time' => 1525009169,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerVL31OCz');
