<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTKTfbtP\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTKTfbtP/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerTKTfbtP.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerTKTfbtP\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerTKTfbtP\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'TKTfbtP',
    'container.build_id' => '1070f504',
    'container.build_time' => 1525210133,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerTKTfbtP');
